# Generated by Django 5.2.6 on 2025-09-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post',
        ),
    ]
