databases:
  - name: codeleap_backend_testdb
    plan: free
    databaseName: codeleap_backend_test
    user: codeleap_backend_test

services:
  - type: web
    plan: free
    name: codeleap_backend_test
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn codeleap_backend_test.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codeleap_backend_testdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4